name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.7
      uses: clupprich/ruby-build-action@master
      with:
        ruby-version: 2.7.0

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Bundle install
      run: |
        cd api
        bundle -j 4 --path vendor/bundle

    - name: Run Tests
      run: |
        bundle exec rake test
